version: '3.7'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    test:
        image: example_image:latest
        volumes:
            - .:/code
        depends_on: 
            - db