name: Continuous Integration
on: [push]
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: docker build -t example_image:latest .
      - name: Run unit tests
        run: docker-compose run test pytest
      - name: Login to DockerHub
        if:  ${{ success() }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Push container image
        run: docker push lpzhang5/example_image:latest