name: Continuous Integration
on:
  push:
    branches:
      - develop
      - master
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag name
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
              echo "TAG=staging" >> $GITHUB_ENV
          else
              echo "TAG=prod" >> $GITHUB_ENV
          fi
      - name: Build container image
        run: docker build -t lpzhang5/example_image:${TAG} .
      - name: Run unit tests
        run: docker-compose run test pytest
      - name: Login to DockerHub
        if:  ${{ success() }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Push container image
        if:  ${{ success() }}
        run: docker push lpzhang5/example_image:${TAG}