name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
                if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                    echo "::set-env name=COMPOSE_SUFFIX::staging"
                    echo "::set-env name=PROJECT::clerk_test"
                elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
                    echo "::set-env name=COMPOSE_SUFFIX::prod"
                    echo "::set-env name=PROJECT::clerk"
                else
                    echo "Please run on either master (prod) or develop (staging) branch"
                    exit 1
                fi