name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
              if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                  echo "::set-env name=TAG::staging"
              else
                  echo "::set-env name=TAG::prod"
              fi