name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set env vars
              run: |
                if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                    echo "::set-env name=COMPOSE_SUFFIX::staging"
                    echo "::set-env name=PROJECT::clerk_test"
                elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
                    echo "::set-env name=COMPOSE_SUFFIX::prod"
                    echo "::set-env name=PROJECT::clerk"
                else
                    echo "Please specify either the develop branch for staging or master branch for prod"
                    exit 1
                fi
            - name: Run deploy script
              run: ./deploy.sh
              shell: bash